# Bird Project FeederWatch Through June 1 2021

In [3]:
# import of librarys needed for this project
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import wrangle
from sklearn.model_selection import train_test_split

In [4]:
# create df from csv file and take a look
df = pd.read_csv('PFW_2021_public.csv')
print('shape:', df.shape)
df.head()

shape: (2897105, 22)

,loc_id,latitude,longitude,subnational1_code,entry_technique,sub_id,obs_id,Month,Day,Year,...,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method
0,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059258900,1,24,2021,...,1,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
1,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059259256,1,24,2021,...,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
2,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059259639,1,24,2021,...,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
3,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,OBS1017001338,11,23,2020,...,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4
4,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,OBS1017001339,11,23,2020,...,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4

In [5]:
# look at some of the df details of the types in the df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2897105 entries, 0 to 2897104
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   loc_id              object
 1   latitude            float64
 2   longitude           float64
 3   subnational1_code   object
 4   entry_technique     object
 5   sub_id              object
 6   obs_id              object
 7   Month               int64
 8   Day                 int64
 9   Year                int64
 10  PROJ_PERIOD_ID      object
 11  species_code        object
 12  how_many            int64
 13  valid               int64
 14  reviewed            int64
 15  day1_am             int64
 16  day1_pm             int64
 17  day2_am             int64
 18  day2_pm             int64
 19  effort_hrs_atleast  float64
 20  snow_dep_atleast    float64
 21  Data_Entry_Method   object
dtypes: float64(4), int64(10), object(8)
memory usage: 486.3+ MB

In [6]:
print('There are %d missing values in total.' % df.isna().sum().sum())

There are 355355 missing values in total.

In [7]:
#get some detail on the numbers
df.describe()

,latitude,longitude,Month,Day,Year,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast
count,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.892591e+06,2.642502e+06
mean,4.070439e+01,-8.708081e+01,5.135655e+00,1.612868e+01,2.020698e+03,3.716377e+00,9.929744e-01,3.085494e-03,9.116953e-01,7.858224e-01,8.924702e-01,7.734052e-01,1.781914e+00,2.096626e+00
std,4.610126e+00,1.604554e+01,4.367908e+00,8.583022e+00,4.591886e-01,8.484951e+00,8.352411e-02,5.546147e-02,2.837376e-01,4.102507e-01,3.097856e-01,4.186283e-01,1.922218e+00,4.572139e+00
min,-3.313755e+01,-1.652876e+02,1.000000e+00,1.000000e+00,2.020000e+03,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-03,0.000000e+00
25%,3.837521e+01,-9.334695e+01,2.000000e+00,9.000000e+00,2.020000e+03,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.001000e+00,0.000000e+00
50%,4.113672e+01,-8.060746e+01,3.000000e+00,1.600000e+01,2.021000e+03,2.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.001000e+00,0.000000e+00
75%,4.331610e+01,-7.610979e+01,1.100000e+01,2.300000e+01,2.021000e+03,4.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.001000e+00,1.000000e-03
max,6.551989e+01,8.182617e+01,1.200000e+01,3.100000e+01,2.021000e+03,5.000000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,8.001000e+00,1.500100e+01

In [8]:
# check the counts for the df
df.value_counts()

loc_id     latitude   longitude    subnational1_code  entry_technique      sub_id     obs_id         Month  Day  Year  PROJ_PERIOD_ID  species_code  how_many  valid  reviewed  day1_am  day1_pm  day2_am  day2_pm  effort_hrs_atleast  snow_dep_atleast  Data_Entry_Method
L100032    45.132361  -93.130328   US-MN              PointMaker1.0_2      S76349308  OBS1013052710  11     14   2020  PFW_2021        bkcchi        4         1      0         1        1        1        1        1.001               0.001             PFW Web 4.0.4             1
L4003560   40.249701  -85.668039   US-IN              /GOOGLE_MAP/ZOOM:18  S77898313  OBS1034730477  12     20   2020  PFW_2021        pinsis        6         1      0         1        1        1        1        8.001               0.000             PFW Web 4.1.4             1
                                                                                      OBS1034719670  12     20   2020  PFW_2021        purfin        5         1      0         1        1        1        1        8.001               0.000             PFW Web 4.1.4             1
                                                                                      OBS1034719671  12     20   2020  PFW_2021        rewbla        8         1      0         1        1        1        1        8.001               0.000             PFW Web 4.1.4             1
                                                                                      OBS1034719672  12     20   2020  PFW_2021        rebwoo        2         1      0         1        1        1        1        8.001               0.000             PFW Web 4.1.4             1
                                                                                                                                                                                                                                                                                   ..
L12899038  38.977781  -94.756866   US-KS              /GOOGLE_MAP/ZOOM:15  S83878443  OBS1100723888  3      22   2021  PFW_2021        amerob        1         1      0         1        0        0        1        1.001               0.000             PFW Mobile App v1.1.17    1
                                                                                      OBS1100727113  3      22   2021  PFW_2021        norcar        1         1      0         1        0        0        1        1.001               0.000             PFW Mobile App v1.1.17    1
                                                                                      OBS1100757343  3      22   2021  PFW_2021        bkcchi        1         1      0         1        0        0        1        1.001               0.000             PFW Mobile App v1.1.17    1
                                                                                      OBS1101621888  3      22   2021  PFW_2021        blujay        1         1      0         1        0        0        1        1.001               0.000             PFW Mobile App v1.1.17    1
L9994340   40.785091  -111.862960  US-UT              /GOOGLE_MAP/ZOOM:15  S85767008  OBS1124252129  4      16   2021  PFW_2021        amegfi        2         1      0         1        1        1        1        1.001               0.000             PFW Web 4.1.4             1
Length: 2555669, dtype: int64

In [9]:
# use the summarize function to take a look at our data in a different way
wrangle.summarize(df)

There are total of 355355 missing values in the entire dataframe.

-------------------
=====================================================


Dataframe head:
|    | loc_id    |   latitude |   longitude | subnational1_code   | entry_technique     | sub_id    | obs_id        |   Month |   Day |   Year | PROJ_PERIOD_ID   | species_code   |   how_many |   valid |   reviewed |   day1_am |   day1_pm |   day2_am |   day2_pm |   effort_hrs_atleast |   snow_dep_atleast | Data_Entry_Method      |
|---:|:----------|-----------:|------------:|:--------------------|:--------------------|:----------|:--------------|--------:|------:|-------:|:-----------------|:---------------|-----------:|--------:|-----------:|----------:|----------:|----------:|----------:|---------------------:|-------------------:|:-----------------------|
|  0 | L12782033 |    44.5741 |    -78.2056 | CA-ON               | /GOOGLE_MAP/ZOOM:15 | S79876486 | OBS1059258900 |       1 |    24 |   2021 | PFW_2021         | amtspa         |          1 |       1 |          0 |         0 |         1 |         0 |         1 |                0.001 |                  5 | PFW Mobile App v1.1.17 |
|  1 | L12782033 |    44.5741 |    -78.2056 | CA-ON               | /GOOGLE_MAP/ZOOM:15 | S79876486 | OBS1059259256 |       1 |    24 |   2021 | PFW_2021         | blujay         |          2 |       1 |          0 |         0 |         1 |         0 |         1 |                0.001 |                  5 | PFW Mobile App v1.1.17 |
|  2 | L12782033 |    44.5741 |    -78.2056 | CA-ON               | /GOOGLE_MAP/ZOOM:15 | S79876486 | OBS1059259639 |       1 |    24 |   2021 | PFW_2021         | bkcchi         |          2 |       1 |          0 |         0 |         1 |         0 |         1 |                0.001 |                  5 | PFW Mobile App v1.1.17 |
=====================================================


Dataframe info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2897105 entries, 0 to 2897104
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   loc_id              object
 1   latitude            float64
 2   longitude           float64
 3   subnational1_code   object
 4   entry_technique     object
 5   sub_id              object
 6   obs_id              object
 7   Month               int64
 8   Day                 int64
 9   Year                int64
 10  PROJ_PERIOD_ID      object
 11  species_code        object
 12  how_many            int64
 13  valid               int64
 14  reviewed            int64
 15  day1_am             int64
 16  day1_pm             int64
 17  day2_am             int64
 18  day2_pm             int64
 19  effort_hrs_atleast  float64
 20  snow_dep_atleast    float64
 21  Data_Entry_Method   object
dtypes: float64(4), int64(10), object(8)
memory usage: 486.3+ MB
None
=====================================================


Dataframe Description:
|       |      latitude |      longitude |        Month |          Day |           Year |       how_many |       valid |    reviewed |     day1_am |     day1_pm |     day2_am |     day2_pm |   effort_hrs_atleast |   snow_dep_atleast |
|:------|--------------:|---------------:|-------------:|-------------:|---------------:|---------------:|------------:|------------:|------------:|------------:|------------:|------------:|---------------------:|-------------------:|
| count |   2.89710e+06 |    2.89710e+06 |  2.89710e+06 |  2.89710e+06 |    2.89710e+06 |    2.89710e+06 | 2.89710e+06 | 2.89710e+06 | 2.89710e+06 | 2.89710e+06 | 2.89710e+06 | 2.89710e+06 |          2.89259e+06 |         2.6425e+06 |
| mean  |  40.7044      |  -87.0808      |  5.13566     | 16.1287      | 2020.7         |    3.71638     | 0.992974    | 0.00308549  | 0.911695    | 0.785822    | 0.89247     | 0.773405    |          1.78191     |         2.09663    |
| std   |   4.61013     |   16.0455      |  4.36791     |  8.58302     |    0.459189    |    8.48495     | 0.0835241   | 0.0554615   | 0.283738    | 0.410251    | 0.309786    | 0.418628    |          1.92222     |         4.57214    |
| min   | -33.1376      | -165.288       |  1           |  1           | 2020           |    1           | 0           | 0           | 0           | 0           | 0           | 0           |          0.001       |         0          |
| 25%   |  38.3752      |  -93.3469      |  2           |  9           | 2020           |    1           | 1           | 0           | 1           | 1           | 1           | 1           |          1.001       |         0          |
| 50%   |  41.1367      |  -80.6075      |  3           | 16           | 2021           |    2           | 1           | 0           | 1           | 1           | 1           | 1           |          1.001       |         0          |
| 75%   |  43.3161      |  -76.1098      | 11           | 23           | 2021           |    4           | 1           | 0           | 1           | 1           | 1           | 1           |          1.001       |         0.001      |
| max   |  65.5199      |   81.8262      | 12           | 31           | 2021           | 5000           | 1           | 1           | 1           | 1           | 1           | 1           |          8.001       |        15.001      |
=====================================================
DataFrame value counts:
L3149107     1701
L3275296     1475
L5181157     1445
L8142493     1417
L12753440    1237
             ...
L13887696       1
L12761351       1
L12987109       1
L8142896        1
L14329130       1
Name: loc_id, Length: 17650, dtype: int64
(-33.236999999999995, -23.272]         78
(-23.272, -13.406]                      0
(-13.406, -3.54]                        0
(-3.54, 6.325]                          0
(6.325, 16.191]                         0
(16.191, 26.057]                     1136
(26.057, 35.923]                   432324
(35.923, 45.788]                  2215355
(45.788, 55.654]                   240168
(55.654, 65.52]                      8044
Name: latitude, dtype: int64
(-165.536, -140.576]       5529
(-140.576, -115.865]     336365
(-115.865, -91.153]      463498
(-91.153, -66.442]      2068940
(-66.442, -41.731]        22695
(-41.731, -17.019]            0
(-17.019, 7.692]              0
(7.692, 32.403]               0
(32.403, 57.115]              0
(57.115, 81.826]             78
Name: longitude, dtype: int64
US-NY    246810
CA-ON    232293
US-PA    181677
US-VA    180755
US-CA    120518
          ...
CA-YT       663
XX-         388
PM-         274
US-HI       228
CA-NT       128
Name: subnational1_code, Length: 65, dtype: int64
/GOOGLE_MAP/ZOOM:15                          1249420
/GOOGLE_MAP/ZOOM:18                           443998
POSTCODE LAT/LONG LOOKUP                      229462
ESRI_WEBSERVICE_STREET                        206995
PointMaker1.0_2                               104782
                                              ...
otherQC Topo map   31H02-200-0202                 81
otherMicrosoft Encarta Atlas                      76
otherPFW Mapping Tool                             63
ESRI_WEBSERVICE_STREET/GOOGLE_MAP/ZOOM:-4          9
STATE/GOOGLE_MAP/ZOOM:14                           8
Name: entry_technique, Length: 109, dtype: int64
S85201430    42
S86301833    41
S84390334    41
S82999816    41
S81866420    40
             ..
S78104168     1
S82265061     1
S80798002     1
S86370993     1
S79914062     1
Name: sub_id, Length: 248241, dtype: int64
OBS1080358204    1
OBS1034279889    1
OBS1122002779    1
OBS1046699223    1
OBS1033259700    1
                ..
OBS1044829609    1
OBS1137994199    1
OBS1080599913    1
OBS1171313180    1
OBS1014234377    1
Name: obs_id, Length: 2897105, dtype: int64
(0.988, 2.1]    1126843
(2.1, 3.2]       523735
(3.2, 4.3]       371176
(4.3, 5.4]            0
(5.4, 6.5]            0
(6.5, 7.6]            0
(7.6, 8.7]            0
(8.7, 9.8]            0
(9.8, 10.9]           0
(10.9, 12.0]     875351
Name: Month, dtype: int64
(0.969, 4.0]    307798
(4.0, 7.0]      316711
(7.0, 10.0]     242411
(10.0, 13.0]    297448
(13.0, 16.0]    322669
(16.0, 19.0]    253006
(19.0, 22.0]    340232
(22.0, 25.0]    259746
(25.0, 28.0]    361197
(28.0, 31.0]    195887
Name: Day, dtype: int64
(2019.998, 2020.1]     875351
(2020.1, 2020.2]            0
(2020.2, 2020.3]            0
(2020.3, 2020.4]            0
(2020.4, 2020.5]            0
(2020.5, 2020.6]            0
(2020.6, 2020.7]            0
(2020.7, 2020.8]            0
(2020.8, 2020.9]            0
(2020.9, 2021.0]      2021754
Name: Year, dtype: int64
PFW_2021    2897105
Name: PROJ_PERIOD_ID, dtype: int64
dowwoo     159577
daejun     158907
norcar     158154
houfin     145701
moudov     143259
            ...
yelgro          1
calgna          1
wesfly          1
yegvir          1
commer1         1
Name: species_code, Length: 563, dtype: int64
(-4.0, 500.9]       2897075
(500.9, 1000.8]          25
(1000.8, 1500.7]          2
(1500.7, 2000.6]          0
(2000.6, 2500.5]          0
(2500.5, 3000.4]          1
(3000.4, 3500.3]          0
(3500.3, 4000.2]          0
(4000.2, 4500.1]          0
(4500.1, 5000.0]          2
Name: how_many, dtype: int64
(-0.002, 0.1]      20354
(0.1, 0.2]             0
(0.2, 0.3]             0
(0.3, 0.4]             0
(0.4, 0.5]             0
(0.5, 0.6]             0
(0.6, 0.7]             0
(0.7, 0.8]             0
(0.8, 0.9]             0
(0.9, 1.0]       2876751
Name: valid, dtype: int64
(-0.002, 0.1]    2888166
(0.1, 0.2]             0
(0.2, 0.3]             0
(0.3, 0.4]             0
(0.4, 0.5]             0
(0.5, 0.6]             0
(0.6, 0.7]             0
(0.7, 0.8]             0
(0.8, 0.9]             0
(0.9, 1.0]          8939
Name: reviewed, dtype: int64
(-0.002, 0.1]     255828
(0.1, 0.2]             0
(0.2, 0.3]             0
(0.3, 0.4]             0
(0.4, 0.5]             0
(0.5, 0.6]             0
(0.6, 0.7]             0
(0.7, 0.8]             0
(0.8, 0.9]             0
(0.9, 1.0]       2641277
Name: day1_am, dtype: int64
(-0.002, 0.1]     620495
(0.1, 0.2]             0
(0.2, 0.3]             0
(0.3, 0.4]             0
(0.4, 0.5]             0
(0.5, 0.6]             0
(0.6, 0.7]             0
(0.7, 0.8]             0
(0.8, 0.9]             0
(0.9, 1.0]       2276610
Name: day1_pm, dtype: int64
(-0.002, 0.1]     311525
(0.1, 0.2]             0
(0.2, 0.3]             0
(0.3, 0.4]             0
(0.4, 0.5]             0
(0.5, 0.6]             0
(0.6, 0.7]             0
(0.7, 0.8]             0
(0.8, 0.9]             0
(0.9, 1.0]       2585580
Name: day2_am, dtype: int64
(-0.002, 0.1]     656469
(0.1, 0.2]             0
(0.2, 0.3]             0
(0.3, 0.4]             0
(0.4, 0.5]             0
(0.5, 0.6]             0
(0.6, 0.7]             0
(0.7, 0.8]             0
(0.8, 0.9]             0
(0.9, 1.0]       2240636
Name: day2_pm, dtype: int64
(-0.008, 0.801]     350033
(0.801, 1.601]     1876504
(1.601, 2.401]           0
(2.401, 3.201]           0
(3.201, 4.001]           0
(4.001, 4.801]      513370
(4.801, 5.601]           0
(5.601, 6.401]           0
(6.401, 7.201]           0
(7.201, 8.001]      152684
Name: effort_hrs_atleast, dtype: int64
(-0.016, 1.5]       2056549
(1.5, 3.0]                0
(3.0, 4.5]                0
(4.5, 6.0]           324956
(6.0, 7.5]                0
(7.5, 9.001]              0
(9.001, 10.501]           0
(10.501, 12.001]          0
(12.001, 13.501]          0
(13.501, 15.001]     260997
Name: snow_dep_atleast, dtype: int64
PFW Web 4.1.4                           2337226
PFW Mobile App v1.1.17                   512232
PFW Web 4.0.4                             30917
PFW Mobile App v1.1.14                     9651
PFW Mobile App v1.1.16                     6957
PFW Mobile App vGLOBAL_APP_VER_SHORT         62
PFW Mobile App v1.1.0                        32
PFW Web 4.0.2                                28
Name: Data_Entry_Method, dtype: int64
=====================================================
nulls in dataframe by column:
                    num_rows_missing  percent_rows_missing
loc_id                             0              0.000000
latitude                           0              0.000000
longitude                          0              0.000000
subnational1_code                  0              0.000000
entry_technique                96238              3.321868
sub_id                             0              0.000000
obs_id                             0              0.000000
Month                              0              0.000000
Day                                0              0.000000
Year                               0              0.000000
PROJ_PERIOD_ID                     0              0.000000
species_code                       0              0.000000
how_many                           0              0.000000
valid                              0              0.000000
reviewed                           0              0.000000
day1_am                            0              0.000000
day1_pm                            0              0.000000
day2_am                            0              0.000000
day2_pm                            0              0.000000
effort_hrs_atleast              4514              0.155811
snow_dep_atleast              254603              8.788187
Data_Entry_Method                  0              0.000000
=====================================================
nulls in dataframe by row:
  num_cols_missing percent_cols_missing    index
0                0                  0.0  2555669
1                1    4.545454545454546   327593
2                2    9.090909090909092    13767
3                3   13.636363636363635       76
============================================

In [10]:
# Need to determine what to do with all the missing data. Delete, average to closest data point.
# As it is only three columns of data that have missing values and they will not add value for what I
# want to get from this data, I will delete those columns: entry_technique, effort_hrs_atleast and 
# snow_dep_atleast

In [11]:
# drop colmns not needed
df = df.drop(columns=['entry_technique', 'effort_hrs_atleast', 'snow_dep_atleast'])

In [12]:
# take a look at our df again without those columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2897105 entries, 0 to 2897104
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   loc_id             object
 1   latitude           float64
 2   longitude          float64
 3   subnational1_code  object
 4   sub_id             object
 5   obs_id             object
 6   Month              int64
 7   Day                int64
 8   Year               int64
 9   PROJ_PERIOD_ID     object
 10  species_code       object
 11  how_many           int64
 12  valid              int64
 13  reviewed           int64
 14  day1_am            int64
 15  day1_pm            int64
 16  day2_am            int64
 17  day2_pm            int64
 18  Data_Entry_Method  object
dtypes: float64(2), int64(10), object(7)
memory usage: 420.0+ MB

In [13]:
# check for missing values
print('There are %d missing values in total.' % df.isna().sum().sum())

There are 0 missing values in total.

In [ ]:
# setting a function to split the data to use in a wrangle.py file
# splitting the df to build models to test
def train_validate_test_split(df, target, seed=123):
    '''
    This function takes in a dataframe, the name of the target variable
    (for stratification purposes), and an integer for a setting a seed
    and splits the data into train, validate and test. 
    Test is 20% of the original dataset, validate is .30*.80= 24% of the 
    original dataset, and train is .70*.80= 56% of the original dataset. 
    The function returns, in this order, train, validate and test dataframes. 
    '''
    train_validate, test = train_test_split(df, test_size=0.2, 
                                            random_state=seed, 
                                            stratify=df[target])
    train, validate = train_test_split(train_validate, test_size=0.3, 
                                       random_state=seed,
                                       stratify=train_validate[target])
    return train, validate, test